all:
  hosts:
    debian12:
      ansible_host: 192.168.122.12
    fedora39:
      ansible_host: 192.168.122.39
  vars:
    network_dns: 208.67.222.222 208.67.220.220
    doh_server: doh.opendns.com
    pihole_containers: true
