- name: Install Pi-Hole with DNS over HTTPS (DoH)
  hosts: all
  gather_facts: true
  become: true
  handlers:
    - name: Reboot
      ansible.builtin.reboot:

    - name: Restart cloudflared
      ansible.builtin.service:
        name: cloudflared
        state: restarted

  tasks:
    - name: Install as standalone services
      when: pihole_containers is not defined or pihole_containers is false
      ansible.builtin.include_tasks: tasks/standalone.yaml

    - name: Install services as containers
      when: pihole_containers is defined and pihole_containers is true
      ansible.builtin.include_tasks: tasks/containers.yaml
